### ISSUE TITLE
Forget some files in npmjs.com

### ISSUE THREAD

**Issue by tani** [foliojs/unicode-properties#9]
Hi @foliojs, @devongovett  you forgot to upload a few files to npmjs.com. We cannot use this library now. Can you bump up version?

**Comment by devongovett** [comment]
What’s missing?

**Comment by tani** [comment]
There is no javascript files,

```
$ ls node_modules/unicode-properties
LICENSE  node_modules/  package.json  readme.md
```

**Comment by devongovett** [comment]
Should be fixed by 8737993081b3c52890990f3d80060635ea0c1d7d in v1.2.1. npm's `files` config is not very intuitive 😦.

**Comment by tani** [comment]
Thanks!

**Comment by tani** [comment]
@devongovett Oh, excuse me? you still forget to update package.json because you wrote `"main": "dist/unicode-properties.cjs.js"` there. we still cannot use your library as cjs. You should update it to `"main": "unicode-properties.cjs.js"`.

I agree what you said. npm not intuitive for developers.

**Comment by devongovett** [comment]
wow, I'm on a roll. should be fixed in v1.2.2.
